version: '3'

services:
  web:
    build: ./web
    restart: always
    user: 1000:1000
    command: bash -c "python wait-for-postgres.py && python manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    volumes:
    - ./web/lpr_project:/lpr_project
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    depends_on:
    - db
  db:
    image: postgres:11.2
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
