version: '3'

services:
  web:
    build: ./web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    volumes:
    - ./web/lpr_project:/lpr_project
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    restart: on-failure
    depends_on:
    - db
  db:
    image: postgres:11.2
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
