#!/bin/bash
python manage.py collectstatic
python manage.py migrate
python manage.py makemigrations accounts_app departments_app news_app people_app principles_app
python manage.py migrate

# python manage.py cities_light
