# Generated by Django 2.1.5 on 2019-01-30 12:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news_app.utils.get_file_path, verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='URL')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('publishtime', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updatetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Статус')),
                ('updated', models.BooleanField(default=False, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-publishtime',),
            },
        ),
    ]
