# Generated by Django 2.1.5 on 2019-02-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter subject of Opinion', max_length=100, verbose_name='Предмет обсуждения')),
                ('content', models.TextField(help_text='Enter content for Opinion', verbose_name='Точка зрения')),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter content for this Principle', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('LIB', 'Либертарианство'), ('SOC', 'Социальная поддержка'), ('WEAPON', 'Оружие'), ('COPYRIGHT', 'Копирайт'), ('TERMS', 'Терминология')], max_length=10, verbose_name='Предмет обсуждения')),
                ('question', models.TextField(help_text='Enter question text', verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Enter answer text', verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('LAW', 'Констутиционно-правовые реформы'), ('JUSTICE', 'Судебно-правоохранительная реформа'), ('SOCIAL', 'Социальные рефомы'), ('ECONOMIC', 'Экономические реформы'), ('MILITARY', 'Военно-промышленная реформа'), ('FP', 'Внешнеполитическая реформа')], max_length=10, verbose_name='Область применения')),
                ('subheader', models.CharField(help_text='Enter subheader of Reform', max_length=100, verbose_name='Тезис')),
                ('content', models.TextField(help_text='Enter content for Reform', verbose_name='Позиция')),
            ],
        ),
    ]
