# Generated by Django 2.1.5 on 2019-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reform',
            name='header',
            field=models.CharField(choices=[('law', 'Констутиционно-правовые реформы'), ('justice', 'Судебно-правоохранительная реформа'), ('social', 'Социальные рефомы'), ('economic', 'Экономические реформы'), ('military', 'Военно-промышленная реформа'), ('fp', 'Внешнеполитическая реформа')], max_length=10, verbose_name='Область применения'),
        ),
    ]
