# Generated by Django 2.1.5 on 2019-02-07 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principles_app', '0002_auto_20190207_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter content for Opinion', verbose_name='Точка зрения'),
        ),
    ]
