# Generated by Django 2.1.5 on 2019-02-07 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principles_app', '0003_auto_20190207_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reform',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter content for Reform', verbose_name='Позиция'),
        ),
    ]
