# Generated by Django 2.1.5 on 2019-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principles_app', '0004_auto_20190207_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='subject',
            field=models.CharField(choices=[('lib', 'Либертарианство'), ('soc', 'Социальная поддержка'), ('weapon', 'Оружие'), ('copyright', 'Копирайт'), ('terms', 'Терминология')], max_length=10, verbose_name='Предмет обсуждения'),
        ),
    ]
